kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oidc-dev-view
subjects:
  - kind: User
    name: your@email
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io